//======================================================================================================================
//	[A]tari [G]ame [T]ools / dml 2020
//======================================================================================================================

//----------------------------------------------------------------------------------------------------------------------
//	tutorial: Giant Sprites (composite sprites) with and without occlusion maps
//----------------------------------------------------------------------------------------------------------------------
//	controls: none
//----------------------------------------------------------------------------------------------------------------------
//	notes:
//	+	EMS/EMX sprites wider than 32 pixels must be generated with the -emc switch ('composite' type).
//	+	composite sprites must not use the EMSPRQ/EMXSPRQ fastpath drawing modes. use only EMSPR/EMXSPR.
//	+	x-clipping of large sprites is achieved using a larger x-guardband, configured to 64 in the playfield
//		EMX sprites must be cut with -emgx 64 to ensure the generated files match the guardband size.
//	+	occlusion maps are generated by adding the -ocm switch and only works for composite sprites (-emc)
//	+	sprites generated with -ocm will only refresh properly when the playfield has PFA_OcclusionMaps attribute
//	+	occlusion maps can only be used with single-layer, 16x16 tile backgrounds.
//	+	occlusion maps use dirty tile states to refresh the footprint of the sprites using them. this means
//		overlapping sprites will only refresh the tiles below them once.
//	+	occlusion maps are inefficient for moderate to small sprites. they can provide savings for very large
//		sprites with a regular silhouette, few holes. especially if multiple such objects overlap.
//	+	further savings can be achieved by using EntityOccludeVisible to eliminate the opaque interiors of
//		sprites from their refresh footprint. this provides the most gain if the sprite is stationary or 
//		moving very slowly.
//	+	when using EntityOccludeVisible, note that opaque areas of such sprites will combine, further increasing
//		gains when objects overlap.
//
//	additional:

//----------------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------------
//	system headers

#include <mint/sysbind.h>
#include <stdio.h>

// ---------------------------------------------------------------------------------------------------------------------
//	Our AGT headers

#include "agtsys/common_cpp.h"

// basic memory interface
#include "agtsys/ealloc.h"
//#include "agtsys/compress.h"

// machine stuff
#include "agtsys/system.h"

// display stuff
#include "agtsys/shifter.h"

// keyboard, joysticks & mouse
//#include "agtsys/input.h"

// background stuff
#include "agtsys/tileset.h"
#include "agtsys/worldmap.h"
#include "agtsys/playfield.h"
#include "agtsys/arena.h"

// sprite stuff
#include "agtsys/spritesheet.h"
#include "agtsys/slabsheet.h"
#include "agtsys/spritelib.h"

// entity/gameobject interface
#include "agtsys/entity.h"

// ---------------------------------------------------------------------------------------------------------------------7
// define some entity types

enum EntityType : int
{
	// special viewport entity, tracks visible world
	EntityType_VIEWPORT,

	// small/medium sprites
	EntityType_32,
	EntityType_48,
	EntityType_64,

	// large sprites with occlusion maps
	EntityType_80,
	EntityType_144,
	
	// end!
	EntityType_MAX_
};

// ---------------------------------------------------------------------------------------------------------------------7
// some things we currently need to define even if we don't use them

static entity_t *s_pe_viewport = NULL;

drawcontext_t drawcontext;

// ---------------------------------------------------------------------------------------------------------------------
//	hardware interfaces

// interface to hardware claim (for save/restore & clean exit)
machine machinestate;

// interface to STE display services
shifter_ste shift;

// ---------------------------------------------------------------------------------------------------------------------
//	MiNTlib builds need need to define a local superstack. otherwise, AGT does it during CRT startup.
// ---------------------------------------------------------------------------------------------------------------------

S_SUPER_SSP(AGT_CONFIG_STACK);

AGT_MAIN;

// ---------------------------------------------------------------------------------------------------------------------
//	define some space for the display.

// physical display size
#define SCREEN_XSIZE (320)
#define SCREEN_YSIZE (240)

// virtual display size including h-scroll margin
#define VIEWPORT_XSIZE (SCREEN_XSIZE)
#define VIEWPORT_YSIZE (SCREEN_YSIZE)

// ---------------------------------------------------------------------------------------------------------------------
//	configure our scrolling playfield system

// define a playfield config for vertical-only scrolling 
typedef playfield_template
<
    /*tilesize=*/4,
    /*max_scroll=*/8192,
    /*vscroll=*/VScrollMode_LOOPBACK,
    /*hscroll=*/HScrollMode_NONE,
    /*restore=*/RestoreMode_PAGERESTORE,
    /*updatemode=*/UpdateMode_NORMAL,
	/*hwattr=*/PlayfieldHardware				// hardware configuration
	(
		PFH_STE|PFH_Blitter
	),
	/*pfattr=*/PlayfieldAttributes				// enable specific playfield features
	(
		PFA_OcclusionMaps
		//PFA_None
	),
	/*guardx=*/64,								// x guardband size (NOTE: must generate EMX with '-emgx 64')
	/*guardy=*/64								// y guardband size

> playfield_t;

// configure triple-buffering to allow frameslip below 50hz without dropping hard to 25hz
static const int c_num_buffers = 3;

// define an arena (world) composed of 2 such playfields (double-buffered)
typedef arena_template
<
    /*buffers=*/c_num_buffers,
    /*singleframe=*/false,
    /*dualfield=*/false,
    /*playfield_type=*/playfield_t
> arena_t;

// ---------------------------------------------------------------------------------------------------------------------
//	playfield assets

// playfield tile assets
tileset mytiles;

// playfield map assets
worldmap mymap;

// ---------------------------------------------------------------------------------------------------------------------
// sprite assets

// test sprite
spritesheet sprite_asset1;
spritesheet sprite_asset2;
spritesheet sprite_asset3;
spritesheet sprite_asset4;
spritesheet sprite_asset5;

// ---------------------------------------------------------------------------------------------------------------------
//	playfield world coordinates

// clipping margin outside of the scrolling viewport, to accommodate the largest typical sprite before deletion etc.
static const s16 c_viewport_xmargin = playfield_t::c_guardx;
static const s16 c_viewport_ymargin = playfield_t::c_guardy;

// world map safety margin (in pixels) for speculative scrolling algorithm
static const int c_scroll_safety_margin = 16;

// viewport (scroll) starting position in world map
static s16 g_viewport_worldx = 0; 
static s16 g_viewport_worldy = 0;//c_scroll_safety_margin;

// ---------------------------------------------------------------------------------------------------------------------
//	sincos table

#include "tables/sintab32.h"

// =====================================================================================================================
//	program entrypoint
// =====================================================================================================================

int AGT_EntryPoint()
{
	// ---------------------------------------------------------------------------------------------------------------------
	//	welcome message

	printf("[A]tari [G]ame [T]ools / dml 2020\n");

	printf("Sprites: Giant Bosses\n");


	// ---------------------------------------------------------------------------------------------------------------------
	//	detect hardware & configure AGT

	machinestate.configure();


	// ---------------------------------------------------------------------------------------------------------------------
	//	compatibility check for this example

	if (!bSTE && !bMegaSTE)
	{
		// ---------------------------------------------------------------------------------------------------------------------
		// if not one of these machines, complain and bail out...

		printf("unsupported machine!\n");
		printf("press space to quit...\n");
		Crawcin();
	}
	else
	{
		// ---------------------------------------------------------------------------------------------------------------------
		//	...otherwise continue with program


		// ---------------------------------------------------------------------------------------------------------------------
		//	save machine state for a clean exit

		printf("save machine state...\n");
		machinestate.save();
		


		// ---------------------------------------------------------------------------------------------------------------------
		//	shifter (display) initialisation
		//	pull any machine-specific metrics out of the display service & save state before any drawing systems are used

		printf("configure shifter...\n");
		shift.configure();
		shift.save();

		// ---------------------------------------------------------------------------------------------------------------------
		//	load map tiles

		printf("loading tiles...\n");
		mytiles.load_cct("bg.cct");

		// ---------------------------------------------------------------------------------------------------------------------
		//	load map
		
		printf("loading map...\n");
		mymap.load_ccm("bg.ccm");

		// ---------------------------------------------------------------------------------------------------------------------
		//	get map dimensions (x16 -> in pixels) to help keep scroll inside the map limits

		s16 map_xtiles = mymap.getwidth();
		s16 map_ytiles = mymap.getheight();

		s16 map_xpixels = map_xtiles << 4;
		s16 map_ypixels = map_ytiles << 4;

		// max scroll is map size minus screen dimensions (plus safety margin for the scrolling axes)
		s16 map_xlimit = (map_xpixels-VIEWPORT_XSIZE);
		s16 map_ylimit = (map_ypixels-VIEWPORT_YSIZE/*-c_scroll_safety_margin*/);

		// ---------------------------------------------------------------------------------------------------------------------
		//	create an instance of the arena (our game world), connected to the shifter interface

		printf("creating world...\n");
		arena_t myworld(shift, SCREEN_XSIZE, SCREEN_YSIZE);

		// ---------------------------------------------------------------------------------------------------------------------
		//	associate map & tiles with the arena playfield(s)
	
		printf("assigning world map...\n");
		myworld.setmap(&mymap);

		printf("assigning world tiles to each playfield buffer...\n");
		for (int b = myworld.c_num_buffers_-1; b >= 0; b--)
		{
			myworld.select_buffer(b);
			myworld.settiles(&mytiles, &mytiles);
		}

		// ---------------------------------------------------------------------------------------------------------------------
		//	load sprite gfx assets
		// ---------------------------------------------------------------------------------------------------------------------
		//	note: using EMXSPR sprite format

		sprite_asset1.load("b32w.emx");
		sprite_asset2.load("b48w.emx");
		sprite_asset3.load("b64w.emx");
		sprite_asset4.load("b80w.emx");
		sprite_asset5.load("b144w.emx");

		EntityDefAsset_Sprite(EntityType_32,  &sprite_asset1);
		EntityDefAsset_Sprite(EntityType_48,  &sprite_asset2);
		EntityDefAsset_Sprite(EntityType_64,  &sprite_asset3);
		EntityDefAsset_Sprite(EntityType_80,  &sprite_asset4);
		EntityDefAsset_Sprite(EntityType_144, &sprite_asset5);

		// ---------------------------------------------------------------------------------------------------------------------
		//	init world with initial viewport coordinates

		g_viewport_worldx = 0;
		g_viewport_worldy = 640;

		printf("init world viewport...\n");
		myworld.init(g_viewport_worldx, g_viewport_worldy);

		// ---------------------------------------------------------------------------------------------------------------------

		printf("ready... (press key)\n");
		Crawcin();

		// ---------------------------------------------------------------------------------------------------------------------
		//	now claim control over all machine resources - display, timers, input etc.

		printf("claim hardware...\n");
		machinestate.claim();


		// ---------------------------------------------------------------------------------------------------------------------
		//	initialize display
		// ---------------------------------------------------------------------------------------------------------------------

		printf("init shifter...\n");
		shift.set_fieldmode(/*dualfield=*/false);
		shift.init();

		// ---------------------------------------------------------------------------------------------------------------------
		//	load palette for both front and backbuffer 'shiftstates'. we use the tile library palette.

		printf("set palette...\n");	

		for (s16 c = 0; c < 16; ++c)
		{
			// logic (next)
			shift.setcolour(0, 0, c, mytiles.getcol(c));

			// physic (current)
			shift.setcolour(1, 0, c, mytiles.getcol(c));
		}

		// =====================================================================================================================
		//	mainloop setup
		// =====================================================================================================================

		// ---------------------------------------------------------------------------------------------------------------------
		//	initialize entity manager - removes any lingering entities, sets things up for a new session

		EntitySetup(EntityType_MAX_);

		// ---------------------------------------------------------------------------------------------------------------------
		//	create entities needed for this session - Viewport

		// create a viewport entity so we can track its relationship with everything else in the world
		g_pe_viewport = EntitySpawn(EntityType_VIEWPORT, g_viewport_worldx-c_viewport_xmargin, g_viewport_worldy-c_viewport_ymargin);

		// =====================================================================================================================
		//	mainloop
		// =====================================================================================================================

		// ---------------------------------------------------------------------------------------------------------------------
		//	some persistent variables we're going to need in the mainloop

		s16 scroll_speed = 1;			// disable scrolling
		s16 backbuffer_num = 0;			// index of current backbuffer (0 or 1)

		// =====================================================================================================================
		//	spawn objects
		
		entity_t *pe;

		// 32-wide
		pe = EntitySpawn(EntityType_32,  160,120);
		pe->wx = 0; 
		pe->wx = 2048; 
		pe->vx = 33; 
		pe->vy = 37;
		pe = EntitySpawn(EntityType_32,  160,120); 
		pe->wx = 6048; 
		pe->wy = 4096; 
		pe->vx = -47; 
		pe->vy = -41;

		// 48-wide
		pe = EntitySpawn(EntityType_48,  160,120); 
		pe->wx = 0+100; 
		pe->wx = 2048+100; 
		pe->vx = 13; 
		pe->vy = 17;
		pe = EntitySpawn(EntityType_48,  160,120); 
		pe->wx = 2048+100; 
		pe->wy = 4096+100; 
		pe->vx = 24; 
		pe->vy = 21;

		// 64-wide
		pe = EntitySpawn(EntityType_64,  160,120); 
		pe->wx = 3000+300; 
		pe->wx = 1000+100; 
		pe->vx = 9; 
		pe->vy = -13;
		pe = EntitySpawn(EntityType_64,  160,120); 
		pe->wx = 2048+300; 
		pe->wy = 5768+300; 
		pe->vx = 9; 
		pe->vy = 17;

		// 80-wide
		pe = EntitySpawn(EntityType_80,  160,120);
		pe->wx = 3000+200; 
		pe->wx = 1024+250; 
		pe->vx = 15; 
		pe->vy = 12;


/*		pe = EntitySpawn(EntityType_80,  160,120);
		pe->wx = 1024+200; 
		pe->wy = 7000+250; 
		pe->vx = -17; 
		pe->vy = 10;
*/
/*
		// 144-wide
		pe = EntitySpawn(EntityType_144, 160,120); 
		pe->wx = 500+200; 
		pe->wx = 1024+250; 
		pe->vx = -9; 
		pe->vy = 11;
*/

		pe = EntitySpawn(EntityType_144, 160,120); 
		pe->wx = 5000+200; 
		pe->wy = 2500+250; 
		pe->vx = 8; 
		pe->vy = 9;

		// =====================================================================================================================
		//	must link any pending entities before starting mainloop (viewport is an entity and viewport scans rely on it)

		EntityExecuteAllLinks();

		// ---------------------------------------------------------------------------------------------------------------------
		//	start the mainloop - run forever

		while (1)
		{

			// ---------------------------------------------------------------------------------------------------------------------
			//	wait for the current VBL period to elapse

			static s16 s_vblcount = g_vbl;
			shift.wait_vbl_minbound(s_vblcount, 1); // frameslip (smooth transitions below 50z, assuming 3 or 4 buffers)

			// ---------------------------------------------------------------------------------------------------------------------
			//	move viewport

			// manually update the viewport first. we don't need a full tick for this but we do need to keep the viewport sorted
			g_pe_viewport->rx = g_viewport_worldx - c_viewport_xmargin;
			g_pe_viewport->ry = g_viewport_worldy - c_viewport_ymargin;

			// ---------------------------------------------------------------------------------------------------------------------
			//	tick entities, link any new spawns

			EntityTickAll();

			EntityExecuteAllLinks();


			// ---------------------------------------------------------------------------------------------------------------------
			//	update the background & scroll

			// select the next workbuffer (..of two - we're using double buffering here)
			myworld.select_buffer(backbuffer_num % c_num_buffers);

			// update the playfield coordinates for this draw pass
			myworld.setpos(g_viewport_worldx, g_viewport_worldy);

			// restore playfield from any previous drawing
			myworld.bgrestore();

			// get the current draw context, needed for entity drawing
			myworld.get_context(drawcontext, 0, SCREEN_XSIZE, SCREEN_YSIZE);

			// ---------------------------------------------------------------------------------------------------------------------
			//	occlusion mapping: opacity optimization
			//
			//	this is optional!
			//
			//	EntityOccludeVisible subtracts the opaque part of each occlusion-mapped sprite from its footprint
			//	to be repainted. 
			//  this consequently reduces the number of repainted tiles, particularly when the object is
			//  moving slowly. also note that the opaque areas of separate sprites can combine when
			//	overlapped, to reduce repaints even further.

			EntityOccludeVisible(&drawcontext);

			// fill any background tiles required by this change in coordinates
			myworld.hybrid_fill(false);

			// ---------------------------------------------------------------------------------------------------------------------
			//	draw 'all the things'

			EntityDrawVisible(&drawcontext);

			//myworld.dbg_vis_occlusion();

			// ---------------------------------------------------------------------------------------------------------------------
			//	present the current workbuffer as the new frontbuffer

			myworld.activate_buffer();

			// ---------------------------------------------------------------------------------------------------------------------
			//	toggle buffers so next time we write to the new backbuffer

			backbuffer_num++;

			// ---------------------------------------------------------------------------------------------------------------------
			//	update the scroll coordinates

			g_viewport_worldy += scroll_speed;

			// if we hit the end of the map, turn around
			if ((g_viewport_worldy >= map_ylimit) ||
				(g_viewport_worldy < 0/*c_scroll_safety_margin*/))
			{
				// change scroll direction
				g_viewport_worldy -= scroll_speed;
				scroll_speed = -scroll_speed;
				g_viewport_worldy += scroll_speed;
			}

			// ---------------------------------------------------------------------------------------------------------------------
			//	repeat forever...
		}

		// =====================================================================================================================
		//	shutdown: release hardware claim back to TOS
		// =====================================================================================================================

		shift.restore();

		machinestate.restore();

	}

	// ---------------------------------------------------------------------------------------------------------------------
	// back to TOS

	pprintf("terminate...\n");

	return 0;
}

// =====================================================================================================================
// tick function

// tick function for smaller objects with no occlusion maps - allow them to enter the guardband
void shared_fntick_sml(entity_t *_pself)
{
	entity_t& self = *_pself;

	// fetch x,y position offset from sintable
	s32 x = sintab32[self.wx & 8191];
	s32 y = sintab32[self.wy & 8191];

	// advance positions in sintable
	self.wx += self.vx;
	self.wy += self.vy;

	// assign position, relative to viewport
	self.rx = g_viewport_worldx + 160 - self.ox + (x >> 24);
	self.ry = g_viewport_worldy + 120 - self.oy + (y >> 24);
}

// tick function for bigger objects with occlusion maps
// this keeps them out of the guardband until occlusion maps can be clipped against the map bounds (todo)
void shared_fntick_big(entity_t *_pself)
{
	entity_t& self = *_pself;

	// fetch x,y position offset from sintable
	s32 x = sintab32[self.wx & 8191];
	s32 y = sintab32[self.wy & 8191];

	// advance positions in sintable
	self.wx += self.vx;
	self.wy += self.vy;

	// assign position, relative to viewport
	self.rx = g_viewport_worldx + 160 - self.ox + (x >> 24);
	self.ry = g_viewport_worldy + 120 - self.oy + (y >> 25);
}

// =====================================================================================================================
// empty entity dictionary (required)
// =====================================================================================================================

entitydef_t entity_dictionary[EntityType_MAX_] =
{
	// [functions]								[coords]						[control]		[tick state]		[rendering]				[classification properties]
	// tick,collide,asset,hasset				px/y,vx/y,sx/y,ox/y				tickpri,drflag	h,d,frame,counter	drawtype,drawlayer		f_self,f_interactswith	

	// engine objects...

	// viewport
	{ 0,0,0,0,									{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_NONE,0,		EntityFlag_VIEWPORT|EntityFlag_SPATIAL,	0 },

	// other objects...

	// smaller objects - no occlusion maps
	{ &shared_fntick_sml,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_EMXSPRQ,0,	EntityFlag_INERT|EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },
	{ &shared_fntick_sml,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_EMXSPR,0,	EntityFlag_INERT|EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },
	{ &shared_fntick_sml,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_EMXSPR,0,	EntityFlag_INERT|EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },
	// big objects with occlusion maps	
	{ &shared_fntick_big,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_EMXSPR,0,	EntityFlag_INERT|EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },
	{ &shared_fntick_big,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_EMXSPR,0,	EntityFlag_INERT|EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },

};
