//======================================================================================================================
//	[A]tari [G]ame [T]ools / dml 2020
//======================================================================================================================

//----------------------------------------------------------------------------------------------------------------------
//	example: 16x16 tilemap, single-field with tile animation
//----------------------------------------------------------------------------------------------------------------------
//	controls: none
//----------------------------------------------------------------------------------------------------------------------
//	notes:
//		- background held in primary tilemap, animation 'frames' held in secondary tilemap
//		- multiple tilemaps generated by single agtcut command will share a tileset
//		- only tilemaps cut together can share a tileset - maps can't be added after the tileset is emitted
//		- animations can be organised over multiple tilemaps
//		- tilemaps are converted into playfield-ready format when loaded
//		- animation 'frames' are copied to playfield using block copy primitives
//		- cutting multiple tilemaps is mutually exclusive with --stitch-maps mode (outputs one vertically joined map)
//----------------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------------
//	system headers

#include <mint/sysbind.h>
#include <stdio.h>

// ---------------------------------------------------------------------------------------------------------------------
//	Our AGT headers

#include "agtsys/common_cpp.h"

// basic memory interface
#include "agtsys/ealloc.h"
#include "agtsys/compress.h"

// machine stuff
#include "agtsys/system.h"

// display stuff
#include "agtsys/shifter.h"

// keyboard, joysticks & mouse
#include "agtsys/input.h"

// background stuff
#include "agtsys/tileset.h"
#include "agtsys/worldmap.h"
#include "agtsys/playfield.h"
#include "agtsys/arena.h"

// sprite stuff
#include "agtsys/spritesheet.h"
#include "agtsys/slabsheet.h"
#include "agtsys/spritelib.h"

// entity/gameobject interface
#include "agtsys/entity.h"

// audio
#if defined(ENABLE_AGT_AUDIO)
#include "agtsys/sound/sound.h"
#include "agtsys/sound/music.h"
#endif

// titlescreen via pcs
//#include "agtsys/pcs.h"

// random source
#include "agtsys/rnd.h"

// ---------------------------------------------------------------------------------------------------------------------7
//	Game Entity IDs
// ---------------------------------------------------------------------------------------------------------------------7
//	Notes:
//		- add new entities to this index
//		- keep entries matched 1:1 with the entity dictionary table! (entity_dictionary[])
// ---------------------------------------------------------------------------------------------------------------------7

enum EntityType : int
{
	// special viewport entity, tracks visible world
	EntityType_VIEWPORT,

	// sprite object
	EntityType_SPRITE,

	// bg animation proxy objects (invisible sprites)
	EntityType_FACE,
	EntityType_BRAIN,

	// end!
	EntityType_MAX_
};

// ---------------------------------------------------------------------------------------------------------------------

// physical display size
#define SCREEN_XSIZE (320)
#define SCREEN_YSIZE (240)

// virtual display size including h-scroll margin
#define VIEWPORT_XSIZE (SCREEN_XSIZE)
#define VIEWPORT_YSIZE (SCREEN_YSIZE)

// ---------------------------------------------------------------------------------------------------------------------
//	configure our scrolling playfield system

// enable this for dualfield/interlaced rendering (requires 2x playfield graphics)
// otherwise use normal rendering
static const s16 c_dualfield = 0;
// this tweak optimizes dualfield display for 50hz, otherwise set 0 for a 25hz-or-less refresh
// note: at 50hz we need only one buffer for even field, one for odd. at 25hz or below we need 
// to store independent odd/even fields for each front/back buffer so the 50hz interlace can 
// be maintained.
static const s16 c_singlevbl = 0;

// define a playfield config for horizontal-only scrolling using STE HW HSCROLL
typedef playfield_template
<
	/*tilesize=*/4,								// 2^4 for 16x16 bg tiles
	/*max_scroll=*/640,							// maximum scroll distance in pixels (reduce to save a little ram on tables)
	/*vscroll=*/VScrollMode_NONE,				// enable full vscroll
	/*hscroll=*/HScrollMode_SCANWALK,			// enable full hscroll
	/*restore=*/RestoreMode_PAGERESTORE,		// restore from virtual page (verus save/restore for individual objects)
	/*updatemode=*/UpdateMode_NORMAL,			// tile update method (normal=full speculative-margin on STE, partial/vertical on STF)
	/*hwattr=*/PlayfieldHardware				// hardware configuration
	(
		PFH_STE|PFH_Blitter
	),
	/*pfattr=*/PlayfieldAttributes				// enable specific platfield features
	(
		PFA_TileAnimation						// *** REQUIRED FOR BG ANIMATION ***
	),
	64,
	0
> playfield_t;		

// define an arena (world) composed of 2 such playfields (double-buffering on STE)
typedef arena_template
<
	/*buffers=*/2,								// number of framebuffers (playfields) required
	/*singleframe=*/c_singlevbl ? true : false,	// optimise dualfield to half the framebuffer count, when locked @ 50hz
	/*dualfield=*/c_dualfield,					// enable dualfield support at compiletime, otherwise on/off flag will be ignored
	/*playfield_type=*/playfield_t				// playfield config/definition to use for framebuffers
> arena_t;										// new name for our playfield arena definition

arena_t *g_pworld = nullptr;

// ---------------------------------------------------------------------------------------------------------------------
//	machine state interface (setup/shutdown)

machine machinestate;

// ---------------------------------------------------------------------------------------------------------------------
//	MiNTlib builds need need to define a local superstack. otherwise, AGT does it during CRT startup.
// ---------------------------------------------------------------------------------------------------------------------

S_SUPER_SSP(AGT_CONFIG_STACK);

AGT_MAIN;

// ---------------------------------------------------------------------------------------------------------------------

// in 8-way scrolling mode we need to keep a 16 1-tile safety margin between the viewport and the map edges
// otherwise the tile update speculation algorithm will cause draw glitches on scroll direction changes. it renders
// slightly ahead of the scroll and won't wrap on the left or top edges. this safety margin avoids any issues.
static const int c_scroll_safety_margin = 16;

static const s16 c_direction_change_timer = 1024;

// initial scroll & direction (16:16 fixed point)
static s32 g_fscrollx = 0;
static s32 g_fscrolly = 0;
static s32 g_fscrollxdir = 0x00010000>>0; // 1.00 units in x	
static s32 g_fscrollydir = 0x00000000>>0; // 0.00 units in y	

// xlimit at which map stops and changes scroll direction
static s32 g_map_fxlimit = 0;
static s32 g_map_fylimit = 0;

// player viewport coordinates (local, control coordinates, relative to current screen position)
static s16 g_player_viewx = playfield_t::c_guardx;
static s16 g_player_viewy = 0;

// player world coordinates (derived from local coords each frame, for interactions with world & other objects)
static s16 g_player_worldx = playfield_t::c_guardx;
static s16 g_player_worldy = 0;

// viewport (scroll) starting position in world map
static s16 g_viewport_worldx = playfield_t::c_guardx; 
static s16 g_viewport_worldy = 0;

// clipping margin outside of the scrolling viewport, to accommodate the largest typical sprite before deletion etc.
static const s16 c_viewport_xmargin = playfield_t::c_guardx;
static const s16 c_viewport_ymargin = playfield_t::c_guardy;

// pseudorandom number generator
mersenne_twister prng;

// ---------------------------------------------------------------------------------------------------------------------
// static pointers to significant entities (still these must be created the usual way)

// viewport entity is global and part of the entity drawing system
static entity_t *s_pe_viewport = NULL;

drawcontext_t drawcontext;

// ---------------------------------------------------------------------------------------------------------------------

// playfield tile assets
tileset world_tiles;

// playfield map assets
worldmap world_map;
worldmap world_map_anim;

spritesheet sprite_asset;

// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
// =====================================================================================================================
//	program start
// =====================================================================================================================

int AGT_EntryPoint()
{
	// ---------------------------------------------------------------------------------------------------------------------
	//	locate the end of the program to help track memory usage, when USE_MEMTRACE is enabled

	g_tracked_allocation_ += (int)(&end);
#if defined(USE_MEMTRACE)
	printf("ealloc: [%d] initial committed\n", g_tracked_allocation_);
#endif

	// ---------------------------------------------------------------------------------------------------------------------
	//	welcome message

	printf("[A]tari [G]ame [T]ools / dml 2020\n");
	printf("scrolling background with sparse tile animation\n");

	// ---------------------------------------------------------------------------------------------------------------------
	//	open scope before we create any interfaces (so we can expect them to be cleaned up before the scope is closed)
	// ---------------------------------------------------------------------------------------------------------------------
	{
		// ---------------------------------------------------------------------------------------------------------------------
		//	save machine state for a clean exit

		machinestate.configure();

		if (bSTE)
		{	printf("machine: STE\n"); }
		else
		{
			printf("machine not supported. exiting...\n");
			printf("press space...\n");
			Crawcin();
			return -1;
		}

		// ---------------------------------------------------------------------------------------------------------------------

		machinestate.save();

		// ---------------------------------------------------------------------------------------------------------------------
		//	shifter (video) init
	
		// interface to display services
		shifter_ste shift;

		// pulls any machine-specific metrics out of the display service & save state before any drawing systems are used
		shift.configure();
		shift.save();

		// ---------------------------------------------------------------------------------------------------------------------
		//	load map tiles

		printf("loading tiles...\n");
		world_tiles.load_cct("shared.cct");

		// ---------------------------------------------------------------------------------------------------------------------
		//	load maps
		
		printf("loading maps...\n");

		// main backgroundn map
		world_map.load_ccm("bg.ccm");

		// background animations
		world_map_anim.load_ccm("bganim.ccm");

		// get map tile dimensions (x16 -> in pixels) to help keep scroll inside the map limits
		int map_xtiles = world_map.getwidth();
		int map_ytiles = world_map.getheight();
		int map_xsize = map_xtiles << playfield_t::c_tilestep_;
		int map_ysize = map_ytiles << playfield_t::c_tilestep_;

		// scroll starting point (fixedpoint)
		g_fscrollx = 128<<16;//playfield_t::c_guardx<<16;
		g_fscrolly = 0;

		// max scroll is map size minus screen dimensions (plus safety margin)
		g_map_fxlimit = (608-VIEWPORT_XSIZE)<<16;
		g_map_fylimit = ((map_ysize/1)-VIEWPORT_YSIZE-c_scroll_safety_margin)<<16;

		// ---------------------------------------------------------------------------------------------------------------------
		// load sprite

		sprite_asset.load("sprite.ems");

		EntityDefAsset_Sprite(EntityType_SPRITE, &sprite_asset);

		// ---------------------------------------------------------------------------------------------------------------------
		//	create the double-buffered 'world', set the viewport dimensions and connect it to the shifter interface

		printf("creating world...\n");
		arena_t myworld(shift, SCREEN_XSIZE, SCREEN_YSIZE);
		g_pworld = &myworld;

		// ---------------------------------------------------------------------------------------------------------------------
		//	associate map & tiles with the world buffers.
		//	Q: why do we bother to do this manually? 
		//	A: because in dual-field mode each display field can have a different (dithered) tile library
	
		printf("assigning world map...\n");
		myworld.setmap(&world_map);

		pprintf("assigning world tiles...\n");
		for (int b = myworld.c_num_buffers_-1; b >= 0; b--)
		{
			myworld.select_buffer(b);
			pprintf("assigning buffer %d world tileset...\n", b);

			// assign different tiles to each field, but same for both buffers
			myworld.settiles(&world_tiles, &world_tiles);
		}

		// ---------------------------------------------------------------------------------------------------------------------
		//	init world, set viewport initial position

		// convert fixedpoint to screen coords
		g_viewport_worldx = g_fscrollx>>16;
		g_viewport_worldy = g_fscrolly>>16;

		printf("init world viewport...\n");
		myworld.init(g_viewport_worldx, g_viewport_worldy);

		// ---------------------------------------------------------------------------------------------------------------------

		printf("ready... (press key)\n");
		Crawcin();

		// ---------------------------------------------------------------------------------------------------------------------
		//	now claim control over machine resources - display, timers, input etc.

		machinestate.claim();

		// ---------------------------------------------------------------------------------------------------------------------
		//	initialize display, configure single- or dual-field graphics mode, load palettes for phys & log shiftfields
		// ---------------------------------------------------------------------------------------------------------------------
		// note: there are 2 shiftfields by default, even if there are more than 2 playfield buffers. The shiftfield contains
		// all HW state associated with a single frame, including the framebuffer address, palette, scroll/linewid and other
		// relevant state. They must all be committed at exactly the same time by the displayservice.
		// The logical shifstate is always the one to be written by the game loop because it will not reach the HW registers 
		// until the framebuffers are exchanged.

		printf("init shifter...\n");
		shift.set_fieldmode(/*dualfield=*/false);
		shift.init();

		printf("set palette...\n");	
		for (s16 c = 0; c < 16; ++c)
		{
			// logic (next)
			shift.setcolour(0, 0, c, world_tiles.getcol(c));

			// physic (current)
			shift.setcolour(1, 0, c, world_tiles.getcol(c));
		}

		s16 buffer_index = 0;

		// ---------------------------------------------------------------------------------------------------------------------
		//	initialize entity manager - clears entity chain, populates freelist etc.

		EntitySetup(EntityType_MAX_);

		// ---------------------------------------------------------------------------------------------------------------------
		//	reset the sprite clearing stacks so we don't erase bogus rectangles when we restart the game

		myworld.bgrestore_reset();

		// ---------------------------------------------------------------------------------------------------------------------
		//	reset the scrolling playfield

		// player coords within viewport
		g_player_viewx = 160;
		g_player_viewy = 100;

		// convert fixedpoint to screen coords
		g_viewport_worldx = g_fscrollx>>16;
		g_viewport_worldy = g_fscrolly>>16;

		myworld.reset(g_viewport_worldx, g_viewport_worldy);

		// ---------------------------------------------------------------------------------------------------------------------
		// create the viewport so we can track its relationship with everything else

		s_pe_viewport = EntitySpawn(EntityType_VIEWPORT, 0, 0);

		// select this as the active viewport
		EntitySelectViewport(s_pe_viewport);

		// ---------------------------------------------------------------------------------------------------------------------
		// create 'growing' trees, managed as map edits to 2nd playfield layer by invisible entities
		// tick function for each tree will copy a small map rectangle from

		entity_t *pe;

		pe = EntitySpawn(EntityType_FACE,  552, 64);
		pe = EntitySpawn(EntityType_BRAIN, 496, 16);

		// =====================================================================================================================
		//	must link any pending entities before starting mainloop (viewport is an entity and viewport scans rely on it)

		EntityExecuteAllLinks();

		// =====================================================================================================================
		//	mainloop
		// =====================================================================================================================

mainloop:

			// ---------------------------------------------------------------------------------------------------------------------
			//	convert fixedpoint coordinates to playfield coordinates
			g_viewport_worldx = g_fscrollx>>16;
			g_viewport_worldy = g_fscrolly>>16;

			// ---------------------------------------------------------------------------------------------------------------------
			//	wait for the current VBL period to elapse

			shift.wait_vbl();

			s16 field_index = g_vbl;

			// ---------------------------------------------------------------------------------------------------------------------
			// manually update the viewport first

			s_pe_viewport->rx = g_viewport_worldx - c_viewport_xmargin;
			s_pe_viewport->ry = g_viewport_worldy - c_viewport_ymargin;


			// ---------------------------------------------------------------------------------------------------------------------
			//	tick all currently linked objects

			EntityTickAll();

			// ---------------------------------------------------------------------------------------------------------------------
			//	perform object-object interactions (collision processing)

			//EntityInteractVisible(VIEWPORT_XSIZE, c_viewport_xmargin, VIEWPORT_YSIZE, c_viewport_ymargin);

			// ---------------------------------------------------------------------------------------------------------------------
			//	link any new entities created during [tick] pass. ensures they get drawn in their spawned states *before* next tick

			EntityExecuteAllLinks();

			// ---------------------------------------------------------------------------------------------------------------------
			//	physically remove any entities that were queued for killing during the AI tick pass

			EntityExecuteAllRemoves();

			// ---------------------------------------------------------------------------------------------------------------------
			//	update the background & scroll

			// select the next workbuffer (..of two - we're using double buffering here)
			myworld.select_buffer((buffer_index & 1));

			// ---------------------------------------------------------------------------------------------------------------------

			// restore playfield from any previous drawing
			myworld.bgrestore();

			// update the playfield coordinates for this draw pass
			myworld.setpos(g_viewport_worldx, g_viewport_worldy);

			// fill any background tiles required by this change in coordinates
			myworld.hybrid_fill(false);

			// ---------------------------------------------------------------------------------------------------------------------
			// retrieve playfield [drawcontext] structure for sharing with low-level drawing functions

			myworld.get_context(drawcontext, 0, VIEWPORT_XSIZE, VIEWPORT_YSIZE);

			// ---------------------------------------------------------------------------------------------------------------------
			//	draw 'all the things'

			EntityDrawVisible(&drawcontext);
				
			// ---------------------------------------------------------------------------------------------------------------------
			//	activate the new workbuffer as the next shifter state so it will be presented on the next VBLank

			myworld.activate_buffer();

			// ---------------------------------------------------------------------------------------------------------------------
			//	advance workbuffer (i.e. double buffering of playfields)

			buffer_index++;

			// ---------------------------------------------------------------------------------------------------------------------
			// update scroll coords

			// advance scroll
			g_fscrollx += g_fscrollxdir;

			if ((g_fscrollx >= g_map_fxlimit))
			{
				// bounce off the right side of the map
				g_fscrollx -= g_fscrollxdir;
				g_fscrollxdir = 0;
			}

			// ---------------------------------------------------------------------------------------------------------------------
			//	any remaining CPU time here can be put to good use

		goto mainloop;

		// =====================================================================================================================
		//	end mainloop
		// =====================================================================================================================

		// ---------------------------------------------------------------------------------------------------------------------
		//	restore primary display state

		shift.restore();
	}


	// ---------------------------------------------------------------------------------------------------------------------
	//	restore full machine state

	machinestate.restore();

	// ---------------------------------------------------------------------------------------------------------------------
	// back to TOS

	pprintf("terminate...\n");

	return 0;
}




// =====================================================================================================================
//	entity tick functions
// =====================================================================================================================

// source (tilemap) coords for upper-left of each animation frame, per tree type

int s_face[15][2] =
{
//	{ srcx, srcy }
	{ 0, 0 },
	{ 0, 4 },
	{ 0, 8 },
	{ 0, 12 },
	{ 0, 16 },
	{ 0, 20 },	// open mouth
	{ 0, 16 },
	{ 0, 12 },
	{ 0, 16 },
	{ 0, 20 },	// open mouth
	{ 0, 16 },
	{ 0, 12 },
	{ 0, 8 },
	{ 0, 4 },
	{ 0, 0 },
};

int s_brain[2][2] =
{
//	{ srcx, srcy }
	{ 0, 24 },
	{ 0, 28 },
};

// animation header defines frame count and a set of frame positions
struct animdef_s
{
	int frames;			// number of frames in this animation
	int (*sequence)[2]; // pointer to frame tile positions (x,y tile offsets into map)
};

// library of different animations
animdef_s s_bganims[] =
{
//	{ framecount, framesequence }
	{ 15, s_face },
	{ 2, s_brain },
};

// tick function for just the face animation
void face_fntick(entity_t *_pself)
{
	// get non-aliasable reference to object
	entity_t &self = *_pself;
	
	static const int c_animation_id = 0;

	// process animation every 64'th frame
	if (--self.counter <= 0)
	{
		self.counter = 21;

		// only update BG if viewport is close enough, otherwise it wastes time

		static const int c_proximity = 64;

		if (self.rx >= (g_viewport_worldx-c_proximity) && 
			self.rx <  (g_viewport_worldx+VIEWPORT_XSIZE+c_proximity))
		{
			// get animation sequence for this animation ID
			int (*sequence)[2] = s_bganims[c_animation_id].sequence;

			self.frame++;
			if (self.frame >= s_bganims[c_animation_id].frames) // loop animation
				self.frame = 0;

			// get source (map) coords for this animation frame
			int sx = sequence[self.frame][0];
			int sy = sequence[self.frame][1];

			// copy rectangle from animation map asset to active playfield map
			g_pworld->multimod_copy<PFLayer_Base>
			(
				/*sx=*/sx,
				/*sy=*/sy,
				/*dx=*/self.rx >> 4,
				/*dy=*/self.ry >> 4,
				/*w=*/4,
				/*h=*/4,
				/*source=*/world_map_anim
			);
		}

	}

	// spit sprites on certain BG frames
	if ((self.frame == 5) || (self.frame == 9))
	{
		if ((self.counter & 3) == 0)
		{
			static u16 rand = 44312;

			entity_t *pnew = EntitySpawn(EntityType_SPRITE, 554, 108);
			pnew->fvx = -3 << 16;
			// random vertical spread
			pnew->fvy = (((self.counter + (rand>>5)) & 15)-7) << 12;

			rand += 19283;
			rand *= 62117;
		}
	}

}

// tick function for just the brain animation
void brain_fntick(entity_t *_pself)
{
	// get non-aliasable reference to object
	entity_t &self = *_pself;
	
	static const int c_animation_id = 1;

	// process animation every 64'th frame
	if (--self.counter <= 0)
	{
		self.counter = 8;

		// only update BG if viewport is close enough, otherwise it wastes time

		static const int c_proximity = 64;

		if (self.rx >= (g_viewport_worldx-c_proximity) && 
			self.rx <  (g_viewport_worldx+VIEWPORT_XSIZE+c_proximity))
		{
			// get animation sequence for this animation ID
			int (*sequence)[2] = s_bganims[c_animation_id].sequence;

			// get source (map) coords for this animation frame
			int sx = sequence[self.frame][0];
			int sy = sequence[self.frame][1];

			// copy rectangle from animation map asset to active playfield map
			g_pworld->multimod_copy<PFLayer_Base>
			(
				/*sx=*/sx,
				/*sy=*/sy,
				/*dx=*/self.rx >> 4,
				/*dy=*/self.ry >> 4,
				/*w=*/4,
				/*h=*/4,
				/*source=*/world_map_anim
			);
		}

		self.frame++;
		if (self.frame >= s_bganims[c_animation_id].frames) // loop animation
			self.frame = 0;
	}
}

void sprite_fntick(entity_t *_pself)
{
	// get non-aliasable reference to object
	entity_t &self = *_pself;

	self.frx += self.fvx;
	self.fry += self.fvy;
	if (self.rx < (g_viewport_worldx - 64))
		EntityRemove(_pself);
}

// =====================================================================================================================
// sample entity dictionary. 
// =====================================================================================================================
// note: there are better ways to do this, but the example is meant to be simple to follow more than anything.
//
// this dictionary contains only the 'mostly static' fields from an entity. 'mostly' in the sense that an entity can
// still modify all the fields it wants after it has been created. there are some entity fields however which are used 
// by the engine and do not make sense to pre-define in the dictionary. it also saves time to avoid copying those when 
// spawning a new entity instance.
//
// the process of spawning a new entity should be as simple as possible - copy all the static fields from the dictionary
// over the same fields in the entity instance. internal/dynamic fields are left to the engine.
//
// fields in {0} braces are unions - usually a scalar value which has BOTH 16bit integer AND 32bit fixedpoint reps at
// the same address. here, the initialized value is the integer part (but this can be changed by reordering the union).

entitydef_t entity_dictionary[EntityType_MAX_] =
{
	// [functions]								[coords]						[control]		[tick state]		[rendering]				[classification properties]
	// tick,collide,asset,hidden				px/y,vx/y,sx/y,ox/y				tickpri,drflag	h,d,frame,counter	drawtype,drawlayer		f_self,f_interactswith	

	// engine objects...

	// viewport																					// viewport has no tick
	// Q: why? A: because it's a rectangle and we can determine what is inside it quickly if it is also an entity which moves through the world
	{ 0,0,0,0,									{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_NONE,0,		EntityFlag_VIEWPORT|EntityFlag_SPATIAL,	0 },

	{ &sprite_fntick,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_EMSPR,0,		EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },

	{ &face_fntick,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_NONE,0,		EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },
	{ &brain_fntick,0,0,0,						{0},{0},{0},{0},0,0,0,0,		0,0,			0,0,0,0,			EntityDraw_NONE,0,		EntityFlag_TICKED|EntityFlag_SPATIAL,	0 },
};

//----------------------------------------------------------------------------------------------------------------------
