#!/usr/bin/env python3
# =============================================================================
#  make_usatan_hd.py — Image « carte SD » pour l'UltraSatan émulé : un disque dur
#  ACSI brut avec table de partitions ATARI (secteur racine, entrées à $1C6) et
#  UNE partition GEM (FAT16) que le TOS/EmuTOS monte en C: au boot SANS pilote.
#
#  La partition porte AUTO\USTEST.PRG (tools/make_usatan_test.py, importé) : EmuTOS
#  amorce sur le disque dur dès qu'il en trouve un et lance les AUTO de C: — le
#  programme de test tourne donc DEPUIS la carte SD, comme les outils d'un vrai
#  utilisateur d'UltraSatan. (Un secteur racine exécutable ne servirait à rien :
#  EmuTOS ne l'exécute que sur un disque SANS partition reconnue, disk_try_dmaboot.)
#
#  DÉTERMINISTE (aucune date hôte) : l'image se regénère octet pour octet.
#  Usage : python3 tools/make_usatan_hd.py disks/etalons/usatan_sd.img
#  68000/TOS big-endian pour la table Atari ; BPB FAT little-endian (DOS).
# =============================================================================
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_usatan_test import build_prg, write_fs   # noqa: E402  (programme de test 68000)

SECT = 512
# 16 Mo : il FAUT plus de 4084 clusters. Atari TOS suppose un FAT16 sur tout disque
# dur, mais EmuTOS applique la règle Microsoft (FAT12 ≤ 4084 clusters, sinon FAT16)
# — une partition de 2 Mo (2033 clusters) y était lue en FAT12 et la chaîne de
# AUTO\USTEST.PRG cassait après le 1er cluster. 32766 secteurs tient dans le champ
# 16 bits du BPB ; clusters de 2 secteurs = la convention AHDI des partitions GEM.
TOTAL = 32768
PART_START = 2            # la partition commence au secteur 2 (racine + 1 réservé)
PART_SIZE = TOTAL - PART_START

SPC = 2
RES = 1
NFAT = 2
NROOT = 128
clusters = (PART_SIZE - RES) // SPC
SPF = (clusters * 2 + SECT - 1) // SECT + 1


def build() -> bytes:
    img = bytearray(TOTAL * SECT)

    # --- Secteur racine : table de partitions Atari (AHDI) ---------------------
    # $1C2 : taille du disque en secteurs ; $1C6 : 4 entrées {flag, id[3], start, size}.
    struct.pack_into('>I', img, 0x1C2, TOTAL)
    e = 0x1C6
    img[e] = 0x01                            # flag : partition existante (bit0)
    img[e + 1:e + 4] = b'GEM'                # type GEM (< 32 Mo)
    struct.pack_into('>I', img, e + 4, PART_START)
    struct.pack_into('>I', img, e + 8, PART_SIZE)
    # Pas de zone « bad sectors » ($1CE..) : zéros. Pas de code d'amorçage (somme ≠ $1234).

    # --- Secteur de boot de la partition : BPB (little-endian, convention DOS) ----
    b = PART_START * SECT
    img[b:b + 2] = b'\x60\x1C'              # BRA.S (non bootable : somme ≠ $1234)
    img[b + 2:b + 8] = b'NeoST '
    img[b + 8:b + 11] = b'USD'              # n° de série fixe (déterminisme)
    struct.pack_into('<H', img, b + 0x0B, SECT)
    img[b + 0x0D] = SPC
    struct.pack_into('<H', img, b + 0x0E, RES)
    img[b + 0x10] = NFAT
    struct.pack_into('<H', img, b + 0x11, NROOT)
    struct.pack_into('<H', img, b + 0x13, PART_SIZE)
    img[b + 0x15] = 0xF8                    # media : disque dur
    struct.pack_into('<H', img, b + 0x16, SPF)
    struct.pack_into('<H', img, b + 0x18, 0)   # SPT/heads : sans objet sur ACSI
    struct.pack_into('<H', img, b + 0x1A, 0)
    struct.pack_into('<H', img, b + 0x1C, 0)

    # --- FAT16 ×2 : entrées 0/1 réservées ----------------------------------------
    fat1 = b + RES * SECT
    for base in (fat1, fat1 + SPF * SECT):
        struct.pack_into('<HH', img, base, 0xFFF8, 0xFFFF)
    root = fat1 + NFAT * SPF * SECT
    rootsects = (NROOT * 32 + SECT - 1) // SECT
    data = root + rootsects * SECT

    def set_fat(idx, val):
        for base in (fat1, fat1 + SPF * SECT):
            struct.pack_into('<H', img, base + idx * 2, val)

    # AUTO\USTEST.PRG (clusters 2..), puis un README à la racine.
    prg = build_prg()
    write_fs(img, root, data, SPC, set_fat, 0xFFFF, prg)
    nclu = (len(prg) + SPC * SECT - 1) // (SPC * SECT)
    e = root + 32                                               # 2e entrée racine
    img[e:e + 8] = b'README  '; img[e + 8:e + 11] = b'TXT'; img[e + 11] = 0x20
    struct.pack_into('<H', img, e + 22, 12 << 11)
    struct.pack_into('<H', img, e + 24, (46 << 9) | (8 << 5) | 21)
    readme = (b'UltraSatan SD image generated by NeoST (tools/make_usatan_hd.py).\r\n'
              b'One GEM partition, mounted as C: by TOS/EmuTOS without any driver;\r\n'
              b'AUTO\\USTEST.PRG prints the UltraSatan/NetUSBee verdicts on RS-232.\r\n')
    c = 3 + nclu
    struct.pack_into('<H', img, e + 26, c); struct.pack_into('<I', img, e + 28, len(readme))
    o = data + (c - 2) * SPC * SECT
    img[o:o + len(readme)] = readme
    set_fat(c, 0xFFFF)
    return bytes(img)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__ or "usage: make_usatan_hd.py OUT.img", file=sys.stderr)
        return 2
    data = build()
    with open(sys.argv[1], 'wb') as f:
        f.write(data)
    print(f"UltraSatan SD image -> {sys.argv[1]} ({len(data)} bytes, 1 GEM partition, FAT16, "
          f"AUTO\\USTEST.PRG {len(build_prg())} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
